version: 2.1
working_directory: ~/trade_platform
orbs:
  node: circleci/node@3.0.1
  heroku: circleci/heroku@1.0.1
k6_performance_tests: &k6_performance_tests
  run:
    name: Running k6 tests
    # Download the k6 docker image. Alternatively, download the k6 release binary
    # Mount a volume to access the folder and run the test
    command: |
      docker pull loadimpact/k6:latest
      docker run -i loadimpact/k6:latest run $HOME/trade_platform/k6/performance-test.js

jobs:
  run_performance_tests:
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - *k6_performance_tests
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Running npm install
          command: |
            npm ci
      - run: 
          name: Running npm test
          command: |
            CI=true npm run test --exit --forceExit
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: Build Docker image
          command: |
            docker build -t heroku-dockerize:circleci .
            docker images
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg NODE_ENV=production -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - run_performance_tests
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
