version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor: node/default
    working_directory: ~/back
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running npm test
          command: |
            npm run test
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: Build Docker image
          command: |
            docker build -t heroku-dockerize:circleci .
            docker images
workflows:
  build-test-deploy:
    jobs:
      - build-and-test